name: Build second brain immutably

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - id: site
        uses: tjakobsson/brain@c4b1c5d33b034476afda3b72d20bb6506a34ffdf # v1
        with:
          vault: vault
          output: dist
          strict-links: true
      - run: test -d "${{ steps.site.outputs.output-path }}"
